# GDP_Per_Capita Dataset

We will work on GDP per capita data taken from World Bank

first read data from the csv file
<br> you can use np.genfromtxt() function to read from the file directly
<br>https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.genfromtxt.html
<br> np.genfromtxt() is a nan-aware function

In [1]:
import numpy as np
data=np.genfromtxt("gdp_per_capita.csv",delimiter=";",usecols=np.arange(1,59),skip_header=True)
index=np.genfromtxt("gdp_per_capita.csv",delimiter=";",usecols=0,skip_header=True,dtype=str)
years=np.arange(1960,2018)

In [2]:
data

array([[          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [  59.77732651,   59.87815281,   58.49287383, ...,  569.57792292,
         561.77874627,  585.85006378],
       [          nan,           nan,           nan, ..., 3683.55260741,
        3308.77282846, 4170.31228025],
       ...,
       [ 433.94119359,  444.8962683 ,  461.79823217, ..., 5746.68112703,
        5280.01763276, 6160.73456882],
       [ 234.16619428,  221.72840063,  213.89422877, ..., 1313.88964551,
        1262.98968189, 1509.79701345],
       [ 280.9945858 ,  283.31586904,  279.4409888 , ..., 1033.41584138,
        1029.07664856, 1079.60829053]])

## Let's get row for Turkey

In [3]:
(index=="Turkey").sum()

1

In [4]:
data_turkey=data[index=="Turkey"]

In [5]:
data_turkey

array([[  509.42411175,   285.01270894,   309.44690335,   350.66322267,
          369.58378635,   385.64097575,   445.25049146,   482.37839397,
          526.21399674,   571.61827375,   489.93077504,   455.10530414,
          558.42156398,   686.49063437,   927.80011041,  1136.37669545,
         1275.95816118,  1427.37325335,  1549.6461278 ,  2079.2227839 ,
         1564.24897993,  1579.07570884,  1402.40808085,  1310.25698781,
         1246.82584157,  1368.40290568,  1510.67808892,  1705.89612038,
         1745.36693883,  2021.86143736,  2794.35355133,  2735.71080727,
         2842.3735983 ,  3180.19201108,  2270.34036225,  2897.87020756,
         3053.95082814,  3144.38945307,  4496.5031695 ,  4108.12787793,
         4316.55389456,  3119.60316704,  3660.06982612,  4718.45675434,
         6040.88490956,  7384.25848221,  8034.60667554,  9709.72002233,
        10850.87038743,  9036.26671065, 10672.40016211, 11340.82361998,
        11720.31386488, 12542.72152945, 12127.46072208, 10984.80

In [15]:
data_turkey.shape

(1, 58)

### Calculate the yearly percentage increase compared to previous year  <br>find the year that has highest increase in terms of percentage.

In [12]:
diff=np.diff(data_turkey)

In [13]:
diff

array([[ -224.41140281,    24.43419441,    41.21631932,    18.92056368,
           16.0571894 ,    59.60951571,    37.12790251,    43.83560277,
           45.40427701,   -81.68749871,   -34.82547089,   103.31625984,
          128.06907039,   241.30947604,   208.57658504,   139.58146573,
          151.41509217,   122.27287445,   529.5766561 ,  -514.97380397,
           14.82672891,  -176.667628  ,   -92.15109304,   -63.43114624,
          121.57706411,   142.27518324,   195.21803147,    39.47081844,
          276.49449853,   772.49211397,   -58.64274405,   106.66279102,
          337.81841278,  -909.85164883,   627.52984532,   156.08062058,
           90.43862493,  1352.11371642,  -388.37529157,   208.42601663,
        -1196.95072752,   540.46665908,  1058.38692821,  1322.42815522,
         1343.37357266,   650.34819332,  1675.11334679,  1141.1503651 ,
        -1814.60367678,  1636.13345146,   668.42345787,   379.4902449 ,
          822.40766457,  -415.26080737, -1142.65552008,  -122.07

In [14]:
diff.shape

(1, 57)

In [17]:
# calculate the percentage difference
percent_diff=(diff/data_turkey[:,:-1])*100

In [18]:
percent_diff

array([[-44.05197902,   8.57301925,  13.31935103,   5.395651  ,
          4.34466824,  15.45725674,   8.33865503,   9.08738934,
          8.62848143, -14.2905681 ,  -7.10824318,  22.70161629,
         22.93411978,  35.15116798,  22.48076743,  12.28302783,
         11.86677563,   8.56628595,  34.17403797, -24.76761066,
          0.94784968, -11.18804038,  -6.57091857,  -4.84112253,
          9.75092592,  10.3971705 ,  12.92254339,   2.31378792,
         15.84162576,  38.20697599,  -2.09861576,   3.89890593,
         11.88508129, -28.60995958,  27.6403422 ,   5.38604594,
          2.9613648 ,  43.00083487,  -8.63727383,   5.07350362,
        -27.72931271,  17.32485288,  28.91712395,  28.02670924,
         22.23802626,   8.80722411,  20.84872869,  11.75265983,
        -16.72311632,  18.10629881,   6.2631034 ,   3.34623179,
          7.01694233,  -3.31077116,  -9.42205088,  -1.11135172,
         -2.96525384]])

we calculated yearly percentage increase, now find the year that has highest increase
<br> for this we can use np.argmax() function. This function returns the index of the maximum element


In [19]:
np.argmax(percent_diff)

37

now find the year that corresponds to the index 37

In [20]:
years

array([1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017])

note that yearly percentage calculation starts from the year 1961

In [21]:
years.shape

(58,)

In [22]:
years_index=years[1:]

In [23]:
years_index

array([1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017])

In [24]:
years_index[37]

1998

the answer is 1998!

### Find the years that GDP per capita decreased compared to the previous year.

In [25]:
np.where(percent_diff<0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 0,  9, 10, 19, 21, 22, 23, 30, 33, 38, 40, 48, 53, 54, 55, 56]))

In [26]:
percent_diff.ravel().shape

(57,)

In [27]:
yearly_percentage_increase=percent_diff.ravel()

In [28]:
indices=np.where(yearly_percentage_increase<0);indices

(array([ 0,  9, 10, 19, 21, 22, 23, 30, 33, 38, 40, 48, 53, 54, 55, 56]),)

let's get the years

In [29]:
years_index[indices]

array([1961, 1970, 1971, 1980, 1982, 1983, 1984, 1991, 1994, 1999, 2001,
       2009, 2014, 2015, 2016, 2017])

## For how many countries is the data available for all the years?

You can use np.isnan function to check a value is NaN or not

In [30]:
a=np.array([np.nan,3.0,5.0])

In [31]:
a

array([nan,  3.,  5.])

In [32]:
np.isnan(a)

array([ True, False, False])

let's go back to our original data array

In [33]:
data

array([[          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [  59.77732651,   59.87815281,   58.49287383, ...,  569.57792292,
         561.77874627,  585.85006378],
       [          nan,           nan,           nan, ..., 3683.55260741,
        3308.77282846, 4170.31228025],
       ...,
       [ 433.94119359,  444.8962683 ,  461.79823217, ..., 5746.68112703,
        5280.01763276, 6160.73456882],
       [ 234.16619428,  221.72840063,  213.89422877, ..., 1313.88964551,
        1262.98968189, 1509.79701345],
       [ 280.9945858 ,  283.31586904,  279.4409888 , ..., 1033.41584138,
        1029.07664856, 1079.60829053]])

In [34]:
np.isnan(data)

array([[ True,  True,  True, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [35]:
nan_data=np.isnan(data).sum(axis=1);nan_data

array([40, 19, 20, 24, 10,  8, 15,  2, 30, 43, 17,  0,  0, 30,  0,  0,  0,
        0,  0, 20, 20,  0, 34, 30,  0,  4,  0,  0, 14,  5, 20,  0,  0,  0,
       30, 10, 48,  0,  0,  0,  0,  0,  0,  0, 20, 20,  0,  0, 12, 58, 56,
       15, 30, 10, 26, 17,  0,  0,  0,  0,  0,  0, 29,  0,  0,  5,  0, 38,
        0, 35, 21,  0, 40,  0,  0,  0, 40, 25,  0,  0, 30,  0, 58, 26,  6,
       10,  4,  0, 17, 11,  0, 43,  0,  0,  0,  0,  0, 35, 31, 31,  0,  0,
        0,  0,  7,  0, 37,  0, 58,  0,  2, 16,  0,  0,  0,  0,  5,  0, 30,
        0, 30, 18, 10,  0,  0,  8,  0, 24, 28,  0, 30, 17,  0, 20, 26, 12,
        0,  5,  0,  0,  0, 35,  0, 35, 22, 58,  0, 16, 35,  0, 20,  8,  0,
       21,  0, 30,  7, 10, 40, 33, 40, 21, 43, 20,  0, 16,  0,  0,  0, 20,
       22,  0,  0, 29,  0,  0,  0, 47,  0,  0,  5, 15,  0,  0,  0,  0, 40,
        0, 30,  0,  1, 58,  0,  5, 34, 15,  0, 22, 10, 27, 29,  0,  0,  8,
        0,  0,  0,  8,  0,  5, 39, 53, 35,  0, 52,  0, 10, 41,  0, 30, 35,
        0,  0, 58,  0, 10

let's find the number of countries that have all the data points for all years

In [36]:
country_number=np.sum(nan_data==0);country_number

123

### get the list of all the countries that have data points for all the years 

In [39]:
indices=np.where(nan_data==0)

In [40]:
index[indices]

array(['Australia', 'Austria', 'Burundi', 'Belgium', 'Benin',
       'Burkina Faso', 'Bangladesh', 'Bahamas, The', 'Belize', 'Bolivia',
       'Brazil', 'Botswana', 'Central African Republic', 'Canada',
       'Chile', 'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.',
       'Congo, Rep.', 'Colombia', 'Costa Rica', 'Caribbean small states',
       'Denmark', 'Dominican Republic', 'Algeria',
       'East Asia & Pacific (excluding high income)',
       'Early-demographic dividend', 'East Asia & Pacific',
       'Europe & Central Asia', 'Ecuador', 'Euro area', 'Spain',
       'European Union', 'Finland', 'Fiji', 'France', 'Gabon',
       'United Kingdom', 'Ghana', 'Greece', 'Guatemala', 'Guyana',
       'High income', 'Hong Kong SAR, China', 'Honduras',
       'Heavily indebted poor countries (HIPC)', 'IBRD only',
       'IDA & IBRD total', 'IDA total', 'IDA blend', 'IDA only', 'India',
       'Ireland', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Kenya', 'St. Kitts 